 # Hook handlers
 
services:
    paustian_quickcheck_module.hook_handler:
        class: Paustian\QuickcheckModule\HookHandler\UiHooksProviderHandler
        arguments:
          - "@request_stack"

    paustian_quickcheck_module.form.examform_type:
        class: Paustian\QuickcheckModule\Form\ExamForm
        arguments:
          - "@translator.default"
        tags:
          - { name: form.type }