 # Hook handlers
 
services:
    paustian_quickcheck_module.hook_handler.quickcheck:
        class: Paustian\QuickcheckModule\HookHandler\HookHandler
        arguments: [@doctrine.entitymanager, @templating]