 # Hook handlers
 
services:
    paustian_quickcheck_module.hook_handler:
        class: Paustian\QuickcheckModule\HookHandler\UiHooksProviderHandler
        arguments:
          - "@request_stack"

    paustian_quickcheck_module.form.examform_type:
        class: Paustian\QuickcheckModule\Form\ExamForm
        arguments:
          - "@translator.default"
        tags:
          - { name: form.type }

    paustian_quickcheck_module.form.tfquestion_type:
            class: Paustian\QuickcheckModule\Form\TFQuestion
            arguments:
              - "@translator.default"
            tags:
              - { name: form.type }

    paustian_quickcheck_module.container.link_container:
        class: Paustian\QuickcheckModule\Container\LinkContainer
        arguments:
          - "@translator.default"
          - "@router"
          - "@zikula_permissions_module.api.permission"
        tags:
          - { name: zikula.link_container }